<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 captain-car.glb --transform --types
Author: cuadot (https://sketchfab.com/cuadot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-acccd15d4e454399a39dbe40f4f6df71
Title: Car
-->

<script lang="ts">
  import { T } from '@threlte/core'
  import {
    useDraco,
    useGltf,
    useGltfAnimations,
    useSuspense,
  } from '@threlte/extras'
  import { asset } from '$app/paths'
  import { Group } from 'three'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type * as THREE from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  ref = new Group()

  type ActionName = 'Idle.1' | 'AllAnim' | 'SpawnClean' | 'Idle.2' | 'Arranque'
  interface GLTFResult {
    nodes: {
      Object_78: THREE.SkinnedMesh
      _rootJoint: THREE.Bone
    }
    materials: {
      Mat_Robot: THREE.MeshStandardMaterial
    }
  }

  const dracoLoader = useDraco()
  const suspend = useSuspense()
  const gltf = suspend(
    useGltf<GLTFResult>(asset('/models/captain-car-transformed.glb'), {
      dracoLoader,
    }),
  )

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)
</script>

<T is={ref} dispose={false} {...props}>
  <!-- eslint-disable-next-line svelte/require-store-reactive-access  -->
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Car" scale={0.05}>
      <T is={gltf.nodes._rootJoint} />
      <T.SkinnedMesh
        name="Object_78"
        castShadow
        receiveShadow
        geometry={gltf.nodes.Object_78.geometry}
        material={gltf.materials.Mat_Robot}
        skeleton={gltf.nodes.Object_78.skeleton}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
