<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 box-man.glb --transform --types --suspense
Author: Zhang Shangbin (https://sketchfab.com/zhangshangbin1314159)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/box-man-3239592d03d849548e4563f07ad95614
Title: Box Man
-->

<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import {
    useDraco,
    useGltf,
    useGltfAnimations,
    useSuspense,
  } from '@threlte/extras'
  import { AnimationUtils, Euler, Group } from 'three'

  import { DEFAULT_ALPHA_TEST } from '@/lib/animations/constants'

  import CharacterClone from './CharacterClone.svelte'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type { Bone, MeshStandardMaterial, SkinnedMesh } from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    opacity = 1,
    lookAt = 0,
    ...props
  }: Props<Group> & {
    ref?: Group
    children?: Snippet<[{ ref: Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    opacity?: number
    lookAt?: number
  } = $props()

  const dracoLoader = useDraco('/draco/')
  const suspend = useSuspense()

  ref = new Group()
  const originalRotation = new Euler()

  let mesh = $state<SkinnedMesh>()
  let joint = $state<Bone>()

  type ActionName = 'walk' | 'idle' | 'jump' | 'running' | 'victory'
  type GLTFResult = {
    nodes: {
      Object_7: SkinnedMesh
      _rootJoint: Bone
    }
    materials: {
      HeZiTou: MeshStandardMaterial
    }
  }

  const gltf = suspend(
    useGltf<GLTFResult>('/models/box-man-transformed.glb', {
      dracoLoader,
    }),
  )

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  $effect(() => {
    const action = $actions.idle

    if (action && mixer && ref) {
      const animationClip = AnimationUtils.subclip(
        action.getClip(),
        'idle',
        0,
        400,
      )

      const clipAction = mixer.clipAction(animationClip, ref)
      clipAction.play()
    }
  })

  $effect(() => {
    if (!mesh) {
      return
    }

    joint = mesh.skeleton.bones.find((bone) => bone.name === 'Head_06')

    if (joint) {
      originalRotation.copy(joint.rotation)
    }
  })

  useTask((dt) => {
    if (mixer) mixer.update(dt * 0.000001)
    if (joint && originalRotation) {
      joint.rotation.copy(originalRotation)
      joint.rotation.x -= 0.75
      joint.rotation.y += lookAt * 0.5
    }
  })
</script>

<T is={ref} dispose={false} visible={opacity >= DEFAULT_ALPHA_TEST} {...props}>
  <!-- eslint-disable-next-line svelte/require-store-reactive-access  -->
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <CharacterClone bind:ref={mesh} {gltf} {opacity} />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
