<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 box-man.glb --transform --types --suspense
Author: Zhang Shangbin (https://sketchfab.com/zhangshangbin1314159)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/box-man-3239592d03d849548e4563f07ad95614
Title: Box Man
-->

<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import {
    Outlines,
    useDraco,
    useGltf,
    useGltfAnimations,
    useSuspense,
  } from '@threlte/extras'
  import { AnimationUtils, Euler, Group } from 'three'
  import { SkeletonUtils } from 'three/examples/jsm/Addons.js'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type { Bone, MeshStandardMaterial, SkinnedMesh } from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    opacity = 1,
    lookAt = 0,
    ...props
  }: Props<Group> & {
    ref?: Group
    children?: Snippet<[{ ref: Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    opacity?: number
    lookAt?: number
  } = $props()

  const dracoLoader = useDraco()
  const suspend = useSuspense()

  ref = new Group()
  const originalRotation = new Euler()

  let mesh = $state<SkinnedMesh>()
  let joint = $state<Bone>()

  type ActionName = 'walk' | 'idle' | 'jump' | 'running' | 'victory'
  type GLTFResult = {
    nodes: {
      Object_7: SkinnedMesh
      _rootJoint: Bone
    }
    materials: {
      HeZiTou: MeshStandardMaterial
    }
  }

  const gltf = suspend(
    useGltf<GLTFResult>('/models/box-man-transformed.glb', {
      dracoLoader,
    }),
  )

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  $effect(() => {
    const action = $actions.idle

    if (action && mixer && ref) {
      const animationClip = AnimationUtils.subclip(
        action.getClip(),
        'idle',
        0,
        400,
      )

      const clipAction = mixer.clipAction(animationClip, ref)
      clipAction.play()
    }
  })

  $effect(() => {
    if (!mesh) {
      return
    }

    joint = mesh.skeleton.bones.find((bone) => bone.name === 'Head_06')

    if (joint) {
      originalRotation.copy(joint.rotation)
    }
  })

  useTask((dt) => {
    if (mixer) mixer.update(dt * 0.000001)
    if (joint && originalRotation) {
      joint.rotation.copy(originalRotation)
      joint.rotation.x -= 0.75
      joint.rotation.y += lookAt * 0.5
    }
  })

  let skinnedMesh: SkinnedMesh | undefined
  let rootJoint: Bone | undefined
</script>

<T is={ref} dispose={false} frustumCulled={false} {...props}>
  <!-- eslint-disable-next-line svelte/require-store-reactive-access  -->
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    {@const clone = SkeletonUtils.clone(gltf.scene)}
    {@const _ = clone.traverse((object: any) => {
      if (object.name === 'Object_7') {
        skinnedMesh = object as SkinnedMesh
        const currentMaterial = skinnedMesh.material as MeshStandardMaterial
        currentMaterial.dispose()
      }
      if (object.name === '_rootJoint') {
        rootJoint = object
      }
    })}
    <T is={rootJoint} />
    <T bind:ref={mesh} is={skinnedMesh} scale={0.01}>
      <T.MeshToonMaterial
        transparent
        {opacity}
        map={gltf.materials.HeZiTou.map}
        roughness={0}
        metalness={0}
      />
      <Outlines color="white" thickness={4} {opacity} transparent />
    </T>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
