<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 box-man.glb --transform --types --suspense
Author: Zhang Shangbin (https://sketchfab.com/zhangshangbin1314159)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/box-man-3239592d03d849548e4563f07ad95614
Title: Box Man
-->

<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import {
    Outlines,
    useDraco,
    useGltf,
    useGltfAnimations,
    useSuspense,
  } from '@threlte/extras'
  import { Group, Vector3 } from 'three'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type { Bone, MeshStandardMaterial, SkinnedMesh } from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    opacity = 1,
    lookAt = 0,
    ...props
  }: Props<Group> & {
    ref?: Group
    children?: Snippet<[{ ref: Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    opacity?: number
    lookAt?: number
  } = $props()

  const dracoLoader = useDraco()
  const suspend = useSuspense()

  ref = new Group()
  const tmpVec3 = new Vector3()

  let mesh = $state<SkinnedMesh>()
  let joint = $state<Bone>()

  type ActionName = 'walk' | 'idle' | 'jump' | 'running' | 'victory'
  type GLTFResult = {
    nodes: {
      Object_7: SkinnedMesh
      _rootJoint: Bone
    }
    materials: {
      HeZiTou: MeshStandardMaterial
    }
  }

  const gltf = suspend(
    useGltf<GLTFResult>('/models/box-man-transformed.glb', {
      dracoLoader,
    }),
  )

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  $effect(() => {
    const action = $actions.idle

    if (action) {
      action.play()
      action.stop()
    }
  })

  $effect(() => {
    if (!mesh) {
      return
    }

    joint = mesh.skeleton.bones.find((bone) => bone.name === 'Head_06')
  })

  $effect(() => {
    if (joint) {
      tmpVec3.set(-1.5 + lookAt, 0, 4)
    }
  })

  useTask((dt) => {
    if (joint) {
      joint.lookAt(tmpVec3)
    }

    if (mixer) mixer.update(dt / 10000)
  })
</script>

<T.AmbientLight intensity={5 * opacity} color={0xeeeeff} />
<T is={ref} dispose={false} {...props}>
  <!-- eslint-disable-next-line svelte/require-store-reactive-access  -->
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T is={gltf.nodes._rootJoint} />
      <T.SkinnedMesh
        bind:ref={mesh}
        name="Object_7"
        geometry={gltf.nodes.Object_7.geometry}
        skeleton={gltf.nodes.Object_7.skeleton}
        scale={0.01}
      >
        <T.MeshToonMaterial
          transparent
          {opacity}
          toneMapped={false}
          map={gltf.materials.HeZiTou.map}
          emissive={0xffffff}
          emissiveIntensity={0.2}
          roughness={0}
          metalness={0}
        />
        <Outlines color="white" thickness={4} />
      </T.SkinnedMesh>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
