<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 boxbot.glb --transform --types
Author: FDU_oficial (https://sketchfab.com/FDU_oficial)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/boxbot-speed-art-525523815fa145da9329fc012d960567
Title: Boxbot Speed art
-->

<script lang="ts">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type * as THREE from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  interface GLTFResult {
    nodes: {
      BOX_0: THREE.Mesh
      DUCTAPE_0: THREE.Mesh
      CIRCUITO_0: THREE.Mesh
      CIRCUITO_1: THREE.Mesh
      CIRCUITO_2: THREE.Mesh
      CIRCUITO_3: THREE.Mesh
      CIRCUITO_4: THREE.Mesh
      CIRCUITO_5: THREE.Mesh
      CIRCUITO_6: THREE.Mesh
      CIRCUITO_7: THREE.Mesh
      PILA003_0: THREE.Mesh
      PILA001_0: THREE.Mesh
      Cylinder001_0: THREE.Mesh
      Cylinder002_0: THREE.Mesh
      Plane002_0: THREE.Mesh
      Cube_0: THREE.Mesh
      Cube_1: THREE.Mesh
      Cube003_0: THREE.Mesh
      Cube003_1: THREE.Mesh
      Cube003_2: THREE.Mesh
      Cube007_0: THREE.Mesh
      Cube007_1: THREE.Mesh
      Cube007_2: THREE.Mesh
      Cube001_0: THREE.Mesh
      Cube009_0: THREE.Mesh
      Cube009_1: THREE.Mesh
      Cube009_2: THREE.Mesh
      Cylinder003_0: THREE.Mesh
      Cylinder003_1: THREE.Mesh
      Cylinder000_0: THREE.Mesh
      Cylinder004_0: THREE.Mesh
      Cube012_0: THREE.Mesh
      Cube012_1: THREE.Mesh
      Circle_0: THREE.Mesh
      Circle_1: THREE.Mesh
      Cube008_0: THREE.Mesh
      Cube008_1: THREE.Mesh
      Cube002_0: THREE.Mesh
      Cube002_1: THREE.Mesh
      Cube004_0: THREE.Mesh
      Cube004_1: THREE.Mesh
      Cube004_2: THREE.Mesh
      Cube005_0: THREE.Mesh
      Cube006_0: THREE.Mesh
      Cube006_1: THREE.Mesh
      Cube006_2: THREE.Mesh
      Cube010_1: THREE.Mesh
      Cube010_0: THREE.Mesh
      Circle001_0: THREE.Mesh
      Circle001_1: THREE.Mesh
      Cube011_0: THREE.Mesh
      Cube011_1: THREE.Mesh
      Cube011_2: THREE.Mesh
      Cube013_0: THREE.Mesh
      Cube013_1: THREE.Mesh
      Plane_0: THREE.Mesh
    }
    materials: {
      CARTON: THREE.MeshStandardMaterial
      CINTA: THREE.MeshStandardMaterial
      ESTAO: THREE.MeshStandardMaterial
      CABLE: THREE.MeshStandardMaterial
      ['CABLE-']: THREE.MeshStandardMaterial
      COPPER: THREE.MeshStandardMaterial
      MOTOR: THREE.MeshStandardMaterial
      THING: THREE.MeshStandardMaterial
      TOPE: THREE.MeshStandardMaterial
      material: THREE.MeshStandardMaterial
      PILA: THREE.MeshStandardMaterial
      ARANDELA: THREE.MeshStandardMaterial
      METAL: THREE.MeshStandardMaterial
      BLACK_PLASTIC: THREE.MeshStandardMaterial
      EYES: THREE.MeshStandardMaterial
      Material: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/boxbot-transformed.glb')
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Group position={[0.08, 1.22, 2.19]} scale={0.04}>
        <T.Mesh
          geometry={gltf.nodes.CIRCUITO_0.geometry}
          material={gltf.materials.ESTAO}
        />
        <T.Mesh
          geometry={gltf.nodes.CIRCUITO_1.geometry}
          material={gltf.materials.CABLE}
        />
        <T.Mesh
          geometry={gltf.nodes.CIRCUITO_2.geometry}
          material={gltf.materials['CABLE-']}
        />
        <T.Mesh
          geometry={gltf.nodes.CIRCUITO_3.geometry}
          material={gltf.materials.COPPER}
        />
        <T.Mesh
          geometry={gltf.nodes.CIRCUITO_4.geometry}
          material={gltf.materials.MOTOR}
        />
        <T.Mesh
          geometry={gltf.nodes.CIRCUITO_5.geometry}
          material={gltf.materials.THING}
        />
        <T.Mesh
          geometry={gltf.nodes.CIRCUITO_6.geometry}
          material={gltf.materials.TOPE}
        />
        <T.Mesh
          geometry={gltf.nodes.CIRCUITO_7.geometry}
          material={gltf.materials.material}
        />
      </T.Group>
      <T.Group position={[-1.25, 0.16, 2.97]} scale={0.14}>
        <T.Mesh
          geometry={gltf.nodes.Cube_0.geometry}
          material={gltf.materials.METAL}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube_1.geometry}
          material={gltf.materials.CINTA}
        />
      </T.Group>
      <T.Group
        position={[-1.35, 0.16, 2.17]}
        rotation={[-1.09, 0, 0]}
        scale={0.14}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube003_0.geometry}
          material={gltf.materials.METAL}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube003_1.geometry}
          material={gltf.materials.CINTA}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube003_2.geometry}
          material={gltf.materials.TOPE}
        />
      </T.Group>
      <T.Group position={[-0.87, 0, 1.01]} rotation={[0.4, 0, 0]} scale={0.35}>
        <T.Mesh
          geometry={gltf.nodes.Cube007_0.geometry}
          material={gltf.materials.METAL}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube007_1.geometry}
          material={gltf.materials.CINTA}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube007_2.geometry}
          material={gltf.materials.TOPE}
        />
      </T.Group>
      <T.Group
        position={[-0.67, 0.14, 1.75]}
        rotation={[-0.2, 0, 0]}
        scale={0.35}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube009_0.geometry}
          material={gltf.materials.METAL}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube009_1.geometry}
          material={gltf.materials.CINTA}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube009_2.geometry}
          material={gltf.materials.TOPE}
        />
      </T.Group>
      <T.Group
        position={[0.45, -0.63, 3.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.26}
      >
        <T.Mesh
          geometry={gltf.nodes.Cylinder003_0.geometry}
          material={gltf.materials.BLACK_PLASTIC}
        />
        <T.Mesh
          geometry={gltf.nodes.Cylinder003_1.geometry}
          material={gltf.materials.EYES}
        />
      </T.Group>
      <T.Group
        position={[-0.89, 0.28, 0.32]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.11, 0.36, 0.36]}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube012_0.geometry}
          material={gltf.materials.THING}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube012_1.geometry}
          material={gltf.materials.METAL}
        />
      </T.Group>
      <T.Group
        position={[-1.42, -0.56, 1.8]}
        rotation={[0.65, Math.PI / 2, 0]}
        scale={0.29}
      >
        <T.Mesh
          geometry={gltf.nodes.Circle_0.geometry}
          material={gltf.materials.BLACK_PLASTIC}
        />
        <T.Mesh
          geometry={gltf.nodes.Circle_1.geometry}
          material={gltf.materials.THING}
        />
      </T.Group>
      <T.Group
        position={[-1.42, -0.56, 1.8]}
        rotation={[0.59, 0, 0]}
        scale={[0.09, 0.15, 0.15]}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube008_0.geometry}
          material={gltf.materials.THING}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube008_1.geometry}
          material={gltf.materials.BLACK_PLASTIC}
        />
      </T.Group>
      <T.Group
        position={[0.29, 0.28, 0.32]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.11, 0.36, 0.36]}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube002_0.geometry}
          material={gltf.materials.THING}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube002_1.geometry}
          material={gltf.materials.METAL}
        />
      </T.Group>
      <T.Group
        position={[0.51, 0.14, 1.75]}
        rotation={[-0.2, 0, 0]}
        scale={0.35}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube004_0.geometry}
          material={gltf.materials.METAL}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube004_1.geometry}
          material={gltf.materials.CINTA}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube004_2.geometry}
          material={gltf.materials.TOPE}
        />
      </T.Group>
      <T.Group position={[0.31, 0, 1.01]} rotation={[0.4, 0, 0]} scale={0.35}>
        <T.Mesh
          geometry={gltf.nodes.Cube006_0.geometry}
          material={gltf.materials.METAL}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube006_1.geometry}
          material={gltf.materials.CINTA}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube006_2.geometry}
          material={gltf.materials.TOPE}
        />
      </T.Group>
      <T.Group
        position={[1.02, -0.56, 1.97]}
        rotation={[0.53, 0, 0]}
        scale={[0.09, 0.15, 0.15]}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube010_1.geometry}
          material={gltf.materials.BLACK_PLASTIC}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube010_0.geometry}
          material={gltf.materials.THING}
        />
      </T.Group>
      <T.Group
        position={[1.02, -0.56, 1.97]}
        rotation={[0.58, Math.PI / 2, 0]}
        scale={0.29}
      >
        <T.Mesh
          geometry={gltf.nodes.Circle001_0.geometry}
          material={gltf.materials.BLACK_PLASTIC}
        />
        <T.Mesh
          geometry={gltf.nodes.Circle001_1.geometry}
          material={gltf.materials.THING}
        />
      </T.Group>
      <T.Group
        position={[1.09, 0.19, 2.28]}
        rotation={[-1.15, 0, 0]}
        scale={0.14}
      >
        <T.Mesh
          geometry={gltf.nodes.Cube011_0.geometry}
          material={gltf.materials.METAL}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube011_1.geometry}
          material={gltf.materials.CINTA}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube011_2.geometry}
          material={gltf.materials.TOPE}
        />
      </T.Group>
      <T.Group position={[1.34, 0.19, 3.08]} scale={0.14}>
        <T.Mesh
          geometry={gltf.nodes.Cube013_0.geometry}
          material={gltf.materials.METAL}
        />
        <T.Mesh
          geometry={gltf.nodes.Cube013_1.geometry}
          material={gltf.materials.CINTA}
        />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.BOX_0.geometry}
        material={gltf.materials.CARTON}
        position={[0, 0, 3.16]}
      />
      <T.Mesh
        geometry={gltf.nodes.DUCTAPE_0.geometry}
        material={gltf.materials.CINTA}
        position={[-0.7, 0.97, 2.92]}
        rotation={[-1.68, 0, 0]}
        scale={0.54}
      />
      <T.Mesh
        geometry={gltf.nodes.PILA003_0.geometry}
        material={gltf.materials.PILA}
        position={[0.52, 1.3, 2.67]}
        rotation={[0.12, -0.27, -0.73]}
        scale={[0.44, 0.44, 0.51]}
      />
      <T.Mesh
        geometry={gltf.nodes.PILA001_0.geometry}
        material={gltf.materials.PILA}
        position={[-0.05, 1.19, 2.61]}
        rotation={[0.01, -0.22, -0.77]}
        scale={[0.44, 0.44, 0.51]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder001_0.geometry}
        material={gltf.materials.ARANDELA}
        position={[1.08, 0.19, 3.09]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.22}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder002_0.geometry}
        material={gltf.materials.ARANDELA}
        position={[-0.92, 0.15, 2.97]}
        rotation={[0, Math.PI / 2, 0]}
        scale={0.19}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane002_0.geometry}
        material={gltf.materials.CINTA}
        position={[-0.57, 0.04, 3.69]}
        scale={0.25}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube001_0.geometry}
        material={gltf.materials.THING}
        position={[-0.55, 0.16, 2.17]}
        scale={[0.21, 0.36, 0.36]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder000_0.geometry}
        material={gltf.materials.ARANDELA}
        position={[0.46, -0.78, 3.06]}
        rotation={[1.65, 0.07, -1.58]}
        scale={[0.21, 0.21, 0.28]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder004_0.geometry}
        material={gltf.materials.ARANDELA}
        position={[-0.43, -0.77, 3.08]}
        rotation={[1.65, -0.1, -1.55]}
        scale={[0.21, 0.21, 0.27]}
      />
      <T.Mesh
        geometry={gltf.nodes.Cube005_0.geometry}
        material={gltf.materials.THING}
        position={[0.63, 0.16, 2.17]}
        scale={[0.21, 0.36, 0.36]}
      />
      <T.Mesh
        geometry={gltf.nodes.Plane_0.geometry}
        material={gltf.materials.Material}
        position={[-0.58, 0.46, -0.27]}
        scale={8.55}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
