<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 fridge.glb --transform --types
Author: sauti (https://sketchfab.com/sauti)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-fridge-f32ec9229a8749d1b79245813fbd6c31
Title: Stylized Fridge
-->

<script lang="ts">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type * as THREE from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  interface GLTFResult {
    nodes: {
      Fridge_Material_0: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/fridge-transformed.glb')
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Fridge_Material_0.geometry}
      material={gltf.materials.Material}
      position={[0.06, 2.2, 0.01]}
      rotation={[-Math.PI / 2, 0, 0]}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
