<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 hard-hat.glb --transform --types
Author: mjkVeggie (https://sketchfab.com/Skeets1418)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/larrys-hard-hat-and-tool-belt-f4e66b09b41447a3b93681c817cce5b6
Title: Larry's Hard Hat and Tool Belt
-->

<script lang="ts">
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type * as THREE from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  interface GLTFResult {
    nodes: {
      Object_4: THREE.Mesh
      Object_5: THREE.Mesh
      Object_6: THREE.Mesh
      Object_7: THREE.Mesh
      Object_8: THREE.Mesh
      Object_10: THREE.Mesh
      Object_11: THREE.Mesh
      Object_12: THREE.Mesh
      Object_14: THREE.Mesh
      Object_15: THREE.Mesh
      mesh_3: THREE.Mesh
      mesh_3_1: THREE.Mesh
      Object_20: THREE.Mesh
      Object_22: THREE.Mesh
      Object_23: THREE.Mesh
      Object_25: THREE.Mesh
      Object_26: THREE.Mesh
      Object_28: THREE.Mesh
      Object_30: THREE.Mesh
      Object_32: THREE.Mesh
    }
    materials: {
      ['Material.021']: THREE.MeshStandardMaterial
      ['Material.025']: THREE.MeshStandardMaterial
      ['Material.027']: THREE.MeshStandardMaterial
      ['Material.033']: THREE.MeshStandardMaterial
      ['Material.035']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/hard-hat-transformed.glb')
</script>

<T.Group bind:ref dispose={false} {...props}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[-1.41, 2.29, -1.69]}
      rotation={[0.08, -0.01, 0.02]}
      scale={[0.11, 0.65, 0.11]}
    >
      <T.Mesh
        geometry={gltf.nodes.Object_4.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_5.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_6.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_7.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_8.geometry}
        material={gltf.materials['Material.025']}
      />
    </T.Group>
    <T.Group
      position={[-1.52, 2.46, -1.99]}
      rotation={[-0.29, -0.43, -0.12]}
      scale={[0.51, 0.51, 0.36]}
    >
      <T.Mesh
        geometry={gltf.nodes.Object_10.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_11.geometry}
        material={gltf.materials['Material.027']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_12.geometry}
        material={gltf.materials['Material.021']}
      />
    </T.Group>
    <T.Group
      position={[-1.23, 1.87, -1.77]}
      rotation={[-3.13, 0.5, -3.11]}
      scale={0.89}
    >
      <T.Mesh
        geometry={gltf.nodes.Object_14.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_15.geometry}
        material={gltf.materials['Material.021']}
      />
    </T.Group>
    <T.Group
      position={[-1.64, 2.64, -1.71]}
      rotation={[3.09, -0.03, -3.14]}
      scale={0.11}
    >
      <T.Mesh
        geometry={gltf.nodes.mesh_3.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.mesh_3_1.geometry}
        material={gltf.materials['Material.021']}
      />
    </T.Group>
    <T.Group
      position={[-1.31, 1.3, 1.46]}
      rotation={[3.08, -1.2, 3.03]}
      scale={0.14}
    >
      <T.Mesh
        geometry={gltf.nodes.Object_22.geometry}
        material={gltf.materials['Material.025']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_23.geometry}
        material={gltf.materials['Material.035']}
      />
    </T.Group>
    <T.Group position={[-0.03, 2.51, 0]} scale={[1.8, 2.89, 1.8]}>
      <T.Mesh
        geometry={gltf.nodes.Object_25.geometry}
        material={gltf.materials['Material.021']}
      />
      <T.Mesh
        geometry={gltf.nodes.Object_26.geometry}
        material={gltf.materials['Material.021']}
      />
    </T.Group>
    <T.Mesh
      geometry={gltf.nodes.Object_20.geometry}
      material={gltf.materials['Material.033']}
      position={[0.04, 8.51, 0.06]}
      rotation={[-0.01, -0.02, -0.02]}
      scale={[1.59, 1.57, 1.48]}
    />
    <T.Mesh
      geometry={gltf.nodes.Object_28.geometry}
      material={gltf.materials['Material.021']}
      position={[-1.54, 2.29, 1.75]}
      rotation={[-0.01, -0.82, 0.01]}
      scale={0.27}
    />
    <T.Mesh
      geometry={gltf.nodes.Object_30.geometry}
      material={gltf.materials['Material.021']}
      position={[-1.83, 2.48, 0.33]}
      rotation={[0, 0.33, -1.55]}
      scale={[0.15, 0.16, 0.18]}
    />
    <T.Mesh
      geometry={gltf.nodes.Object_32.geometry}
      material={gltf.materials['Material.021']}
      position={[-1.69, 2.39, 0.57]}
      rotation={[-1.21, 0.14, -0.25]}
      scale={0.05}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
