<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 box-man.glb --transform --types --suspense
Author: Zhang Shangbin (https://sketchfab.com/zhangshangbin1314159)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/box-man-3239592d03d849548e4563f07ad95614
Title: Box Man
-->

<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import {
    useDraco,
    useGltf,
    useGltfAnimations,
    useSuspense,
  } from '@threlte/extras'
  import { utils } from 'animejs'
  import { AnimationUtils, Group } from 'three'
  import { SkeletonUtils } from 'three/examples/jsm/Addons.js'

  import { windowState } from '@/lib/contexts/Window'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type {
    AnimationAction,
    Bone,
    MeshStandardMaterial,
    SkinnedMesh,
  } from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    opacity = 1,
    ...props
  }: Props<Group> & {
    ref?: Group
    children?: Snippet<[{ ref: Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    opacity?: number
  } = $props()

  const dracoLoader = useDraco()
  const suspend = useSuspense()

  let walkingAnimationClip = $state<AnimationAction>()
  let idleAnimationClip = $state<AnimationAction>()
  ref = new Group()

  type ActionName = 'walk' | 'idle' | 'jump' | 'running' | 'victory'
  type GLTFResult = {
    nodes: {
      Object_7: SkinnedMesh
      _rootJoint: Bone
    }
    materials: {
      HeZiTou: MeshStandardMaterial
    }
  }

  const gltf = suspend(
    useGltf<GLTFResult>('/models/box-man-transformed.glb', {
      dracoLoader,
    }),
  )

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  $effect(() => {
    const walkingAction = $actions.walk
    const idleAction = $actions.idle

    if (
      idleAction &&
      walkingAction &&
      mixer &&
      ref &&
      !walkingAnimationClip &&
      !idleAnimationClip
    ) {
      const walkingClip = AnimationUtils.subclip(
        walkingAction.getClip(),
        'walk',
        400,
        900,
      )

      walkingAnimationClip = mixer.clipAction(walkingClip, ref)
      walkingAnimationClip.setEffectiveWeight(0)
      walkingAnimationClip.play()

      const idleClip = AnimationUtils.subclip(
        idleAction.getClip(),
        'idle',
        0,
        400,
      )

      idleAnimationClip = mixer.clipAction(idleClip, ref)
      idleAnimationClip.setEffectiveWeight(1)
      idleAnimationClip.play()
    }
  })

  useTask((dt) => {
    if (mixer && idleAnimationClip && walkingAnimationClip) {
      const speed = windowState.scrollVelocity
      const acceleration = windowState.scrollAcceleration

      const speedFactor = (acceleration <= 0 ? 0.1 : 8) * speed * dt + 0.01

      if (acceleration <= 0) {
        const weight = utils.clamp(
          walkingAnimationClip.getEffectiveWeight() - speedFactor,
          0,
          1,
        )
        walkingAnimationClip.setEffectiveWeight(weight)
        idleAnimationClip.setEffectiveWeight(1 - weight)
      } else {
        const weight = utils.clamp(
          walkingAnimationClip.getEffectiveWeight() + speedFactor,
          0,
          1,
        )
        walkingAnimationClip.setEffectiveWeight(weight)
        idleAnimationClip.setEffectiveWeight(1 - weight)
      }
      mixer.update(speed * 0.1 * dt)
    }
  })

  let skinnedMesh: SkinnedMesh | undefined
  let rootJoint: Bone | undefined
</script>

<T is={ref} dispose={false} {...props}>
  <!-- eslint-disable-next-line svelte/require-store-reactive-access  -->
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    {@const clone = SkeletonUtils.clone(gltf.scene)}
    {@const _ = clone.traverse((object: any) => {
      if (object.name === 'Object_7') {
        skinnedMesh = object as SkinnedMesh
        const currentMaterial = skinnedMesh.material as MeshStandardMaterial
        currentMaterial.dispose()
      }
      if (object.name === '_rootJoint') {
        rootJoint = object
      }
    })}
    {#if rootJoint}
      <T is={rootJoint} />
    {/if}
    {#if skinnedMesh}
      <T is={skinnedMesh} scale={0.001}>
        <T.MeshToonMaterial
          transparent
          {opacity}
          map={gltf.materials.HeZiTou.map}
          roughness={0}
          metalness={0}
        />
      </T>
    {/if}
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
