<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 box-man.glb --transform --types --suspense
Author: Zhang Shangbin (https://sketchfab.com/zhangshangbin1314159)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/box-man-3239592d03d849548e4563f07ad95614
Title: Box Man
-->

<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import {
    useDraco,
    useGltf,
    useGltfAnimations,
    useSuspense,
  } from '@threlte/extras'
  import { AnimationUtils, Group } from 'three'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type { Bone, MeshStandardMaterial, SkinnedMesh } from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    opacity = 1,
    ...props
  }: Props<Group> & {
    ref?: Group
    children?: Snippet<[{ ref: Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
    opacity?: number
  } = $props()

  const dracoLoader = useDraco()
  const suspend = useSuspense()

  ref = new Group()

  type ActionName = 'walk' | 'idle' | 'jump' | 'running' | 'victory'
  type GLTFResult = {
    nodes: {
      Object_7: SkinnedMesh
      _rootJoint: Bone
    }
    materials: {
      HeZiTou: MeshStandardMaterial
    }
  }

  const gltf = suspend(
    useGltf<GLTFResult>('/models/box-man-transformed2.glb', {
      dracoLoader,
    }),
  )

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  $effect(() => {
    const action = $actions.walk

    if (action && mixer && ref) {
      const clip = AnimationUtils.subclip(action.getClip(), 'walk', 400, 900)

      const clipAction = mixer.clipAction(clip, ref)
      clipAction.play()
    }
  })

  useTask((dt) => {
    if (mixer) mixer.update(dt * 0.1)
  })
</script>

<T.AmbientLight intensity={5 * opacity} color={0xeeeeff} />
<T is={ref} dispose={false} {...props}>
  <!-- eslint-disable-next-line svelte/require-store-reactive-access  -->
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T is={gltf.nodes._rootJoint} />
      <T.SkinnedMesh
        name="Object_7"
        geometry={gltf.nodes.Object_7.geometry}
        skeleton={gltf.nodes.Object_7.skeleton}
        scale={0.01}
      >
        <T.MeshToonMaterial
          transparent
          {opacity}
          map={gltf.materials.HeZiTou.map}
          emissive={0xffffff}
          emissiveIntensity={0.2}
          roughness={0}
          metalness={0}
        />
      </T.SkinnedMesh>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
