<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 converyer-belt.glb --transform --types
Author: K144U (https://sketchfab.com/pathaksankalp04)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-conveyer-belt-2142b1ab5bf2458cab694f64892b7b63
Title: animated conveyer belt
-->

<script lang="ts">
  import { T } from '@threlte/core'
  import {
    useDraco,
    useGltf,
    useGltfAnimations,
    useSuspense,
  } from '@threlte/extras'
  import { asset } from '$app/paths'
  import { Group } from 'three'

  import type { Props } from '@threlte/core'
  import type { Snippet } from 'svelte'
  import type * as THREE from 'three'

  let {
    fallback,
    error,
    children,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  ref = new Group()

  type ActionName =
    | 'Cube.003|Cube.002Action.002'
    | 'Cube.003|Cube.002Action.003'
    | 'Cube.003|Cube.002Action.004'
    | 'Cube.003|Cube.002Action.005'
    | 'Cube.004|Cube.002Action.001'
    | 'Cube.004|Cube.002Action.002'
    | 'Cube.004|Cube.002Action.003'
    | 'Cube.004|Cube.002Action.004'
    | 'Cube.004|Cube.002Action.005'
    | 'Cube.005|Cube.002Action.001'
    | 'Cube.005|Cube.002Action.002'
    | 'Cube.005|Cube.002Action.003'
    | 'Cube.005|Cube.002Action.004'
    | 'Cube.005|Cube.002Action.005'
    | 'Cube.007|Cube.002Action.003'
    | 'Cube.007|Cube.002Action.004'
    | 'Cube.007|Cube.002Action.005'
    | 'Cube.007|Plane.001Action.002'
    | 'Cube.008|Cube.002Action.001'
    | 'Cube.008|Cube.002Action.002'
    | 'Cube.008|Cube.002Action.003'
    | 'Cube.008|Cube.002Action.004'
    | 'Cube.008|Cube.002Action.005'
    | 'Cube.008|Plane.001Action.002'
    | 'Cube.009|Cube.002Action.001'
    | 'Cube.009|Cube.002Action.002'
    | 'Cube.009|Cube.002Action.003'
    | 'Cube.009|Cube.002Action.004'
    | 'Cube.009|Cube.002Action.005'
    | 'Cube.009|Plane.001Action.002'
    | 'Cube.002|Cube.002Action.001'
    | 'Cube.002|Cube.002Action.002'
    | 'Cube.002|Cube.002Action.003'
    | 'Cube.002|Cube.002Action.004'
    | 'Cube.002|Cube.002Action.005'
    | 'Cube.002|Plane.001Action.002'
    | 'Cube.010|Cube.002Action.001'
    | 'Cube.010|Cube.002Action.002'
    | 'Cube.010|Cube.002Action.003'
    | 'Cube.010|Cube.002Action.004'
    | 'Cube.010|Cube.002Action.005'
    | 'Cube.010|Plane.001Action.002'
  interface GLTFResult {
    nodes: {
      Cube003_Material007_0: THREE.Mesh
      Cube004_Material007_0: THREE.Mesh
      Cube005_Material007_0: THREE.Mesh
      Cube007_Material007_0: THREE.Mesh
      Cube008_Material007_0: THREE.Mesh
      Cube009_Material007_0: THREE.Mesh
      Cube002_Material007_0: THREE.Mesh
      Cube010_Material007_0: THREE.Mesh
      Plane001_Material003_0: THREE.Mesh
      Cube_Material004_0: THREE.Mesh
      Cube001_Material002_0: THREE.Mesh
      Plane002_Material009_0: THREE.Mesh
      Cylinder_Material005_0: THREE.Mesh
      Cylinder001_Material005_0: THREE.Mesh
      Cube006_Material007_0: THREE.Mesh
      Cylinder002_Material005_0: THREE.Mesh
      Cylinder003_Material005_0: THREE.Mesh
      Cylinder004_Material005_0: THREE.Mesh
      Cylinder005_Material005_0: THREE.Mesh
    }
    materials: {
      ['Material.007']: THREE.MeshStandardMaterial
      ['Material.003']: THREE.MeshStandardMaterial
      ['Material.004']: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Material.009']: THREE.MeshStandardMaterial
      ['Material.005']: THREE.MeshStandardMaterial
    }
  }

  const suspend = useSuspense()

  const dracoLoader = useDraco()
  const gltf = suspend(
    useGltf<GLTFResult>(asset('/models/conveyer-belt-transformed.glb'), {
      dracoLoader,
    }),
  )
  export const { actions, mixer, ...rest } = useGltfAnimations<ActionName>(
    gltf,
    ref,
  )

  $inspect(actions, mixer, rest)

  $effect(() => {
    Object.values(actions.current).forEach((action) => {
      console.log(action)
      action.play()
    })
  })
</script>

<T is={ref} dispose={false} {...props}>
  <!-- eslint-disable-next-line svelte/require-store-reactive-access  -->
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group
          name="conveyer_belt_fbx"
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group
                name="Cube003"
                position={[452.53, 111.17, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube003_Material007_0"
                  geometry={gltf.nodes.Cube003_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Cube004"
                position={[452.53, 111.17, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube004_Material007_0"
                  geometry={gltf.nodes.Cube004_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Cube005"
                position={[452.53, 111.17, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube005_Material007_0"
                  geometry={gltf.nodes.Cube005_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Cube007"
                position={[20.92, -4.79, 429.92]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube007_Material007_0"
                  geometry={gltf.nodes.Cube007_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Cube008"
                position={[20.92, -4.79, 515.05]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube008_Material007_0"
                  geometry={gltf.nodes.Cube008_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Cube009"
                position={[20.92, 71.19, 429.92]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube009_Material007_0"
                  geometry={gltf.nodes.Cube009_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Cube002"
                position={[452.53, 111.17, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube002_Material007_0"
                  geometry={gltf.nodes.Cube002_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Cube010"
                position={[452.53, 111.17, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube010_Material007_0"
                  geometry={gltf.nodes.Cube010_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Plane001"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Plane001_Material003_0"
                  geometry={gltf.nodes.Plane001_Material003_0.geometry}
                  material={gltf.materials['Material.003']}
                />
              </T.Group>
              <T.Group
                name="Cube"
                position={[0, 52.46, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[322.35, 44.43, 44.31]}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube_Material004_0"
                  geometry={gltf.nodes.Cube_Material004_0.geometry}
                  material={gltf.materials['Material.004']}
                />
              </T.Group>
              <T.Group
                name="Cube001"
                position={[474.49, 124.11, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[100, 100, 126.92]}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube001_Material002_0"
                  geometry={gltf.nodes.Cube001_Material002_0.geometry}
                  material={gltf.materials['Material.002']}
                />
              </T.Group>
              <T.Group
                name="Plane002"
                position={[154.75, -6.85, 0]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={2425.46}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Plane002_Material009_0"
                  geometry={gltf.nodes.Plane002_Material009_0.geometry}
                  material={gltf.materials['Material.009']}
                />
              </T.Group>
              <T.Group
                name="Cylinder"
                position={[-234.13, 43.03, -67.96]}
                scale={26.86}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cylinder_Material005_0"
                  geometry={gltf.nodes.Cylinder_Material005_0.geometry}
                  material={gltf.materials['Material.005']}
                />
              </T.Group>
              <T.Group
                name="Cylinder001"
                position={[247.22, 43.03, -67.96]}
                scale={26.86}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cylinder001_Material005_0"
                  geometry={gltf.nodes.Cylinder001_Material005_0.geometry}
                  material={gltf.materials['Material.005']}
                />
              </T.Group>
              <T.Group
                name="Cube006"
                position={[113.01, -4.79, 429.92]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={36.99}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cube006_Material007_0"
                  geometry={gltf.nodes.Cube006_Material007_0.geometry}
                  material={gltf.materials['Material.007']}
                />
              </T.Group>
              <T.Group
                name="Cylinder002"
                position={[246.5, 32.8, 143.64]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[45.98, 45.98, 51.54]}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cylinder002_Material005_0"
                  geometry={gltf.nodes.Cylinder002_Material005_0.geometry}
                  material={gltf.materials['Material.005']}
                />
              </T.Group>
              <T.Group
                name="Cylinder003"
                position={[-234.88, 32.8, 143.64]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[45.98, 45.98, 51.54]}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cylinder003_Material005_0"
                  geometry={gltf.nodes.Cylinder003_Material005_0.geometry}
                  material={gltf.materials['Material.005']}
                />
              </T.Group>
              <T.Group
                name="Cylinder004"
                position={[246.5, 32.8, -136.92]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[45.98, 45.98, 51.54]}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cylinder004_Material005_0"
                  geometry={gltf.nodes.Cylinder004_Material005_0.geometry}
                  material={gltf.materials['Material.005']}
                />
              </T.Group>
              <T.Group
                name="Cylinder005"
                position={[-234.88, 32.8, -136.92]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[45.98, 45.98, 51.54]}
              >
                <T.Mesh
                  castShadow
                  receiveShadow
                  name="Cylinder005_Material005_0"
                  geometry={gltf.nodes.Cylinder005_Material005_0.geometry}
                  material={gltf.materials['Material.005']}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
